version: '3.8'

services:
  db:
    image: postgres:14.3-alpine
    env_file: .env
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always
  web:
    build: .
    command:  python /usr/src/films/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/films
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
